### ISSUE TITLE
Problem with default keyword arguments 

### ISSUE THREAD

**Issue by gsinclair** [egonSchiele/contracts.ruby#131]
The following code generates the exception shown underneath.

    require 'contracts'
    include Contracts

    Contract ({nfiles:  Nat}) => ArrayOf[String]
    def list(nfiles: 10)
      []
    end

    list(nfiles: 4)      # No problem here.
    list()               # Causes exception

Exception:

    /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts/builtin_contracts.rb:70:in `valid?': undefined method `>=' for nil:NilClass (NoMethodError)
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:249:in `block in make_validator'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:207:in `[]'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:207:in `valid?'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:234:in `block (2 levels) in make_validator'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:233:in `each'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:233:in `all?'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:233:in `block in make_validator'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:303:in `[]'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:303:in `block in call_with'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:298:in `times'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts.rb:298:in `call_with'
      from /Library/Ruby/Gems/2.0.0/gems/contracts-0.8/lib/contracts/decorators.rb:149:in `block in common_method_added'
      from /Users/Gavin/tmp/contracts-bug.rb:23:in `<main>'

I'm calling it a bug because it doesn't give a contract violation message, rather an internal exception in the contracts library itself.

I've not used keyword arguments much, though. Am I right to expect that this code should work?

**Comment by waterlink** [comment]
nfiles: Maybe[Nat]

**Comment by NobbZ** [comment]
The solution is obvious and was kind of known to the op, but the resulting
stacktrace is the actual reported bug, since it is a Ruby trace of method
missing instead of the wrong argument we would expect to come from
contracts.
Am 11.04.2015 11:53 schrieb "Alexey Fedorov" <notifications@github.com>:

**Comment by gsinclair** [comment]
The solution wasn't obvious or known to me (the op) but I can see it now. Thanks. (And yes, I confirm that the stack trace was the reported bug ;)

I'd like for the contract I specified to be a correct contract in that situation. If I specify it as "nfiles: Maybe[Nat]" then it would allow the invocation "list(nfiles: nil)", and that should not be regarded as a correct invocation. 

Taking default values into account when checking whether a function call satisfies a contract. Sounds difficult.

**Comment by nixpulvis** [comment]
Conceptually it shouldmy be hard. But getting access to arguments programatically is potentially treacherous.

**Comment by waterlink** [comment]
Ah, I see, I misunderstood problem entirely while reading it from phone..

**Comment by egonSchiele** [comment]
Fixed on master. Thanks for finding this case!

**Comment by bradfeehan** [comment]
This fixes the runtime error caused when passing nil in, but the logic error remains. The default value is a valid value according to the contract, but [this spec][1] specifies different behaviour to what OP (and I) would expect -- it should pass when not given any parameter because the default value is valid, but when explicitly passing `nil` or a different invalid value, it should fail.

[1]: <https://github.com/egonSchiele/contracts.ruby/blob/bf70488351313db2a42a282957bd9389f9be27f2/spec/ruby_version_specific/contracts_spec_2.0.rb#L32-L34>

**Comment by egonSchiele** [comment]
Ah you are right. That test is incorrect: it should use the default arg if none is given.

**Comment by egonSchiele** [comment]
Hmm, I don't think it is possible to get the default values (not without a lot of hack work).

One possible workaround is to make all the hash values optional.

Example: suppose you have a contract like this:

```ruby
Contract ({name: String, age: Num}) => Person
def person(opts)

end
```

With the current behavior, you have to pass in both a `name` and an `age` to construct a person, otherwise the contract will fail.

With this new behavior, it won't require those params, but will still run the contracts if the params have been given.

**Comment by sfcgeorge** [comment]
I've wondered about this. I don't think making hash values optional all the time is the answer, it doesn't make sense to me—if you've specified a contract then surely you want a value, else you'd use maybe. With an options hash I guess it could make sense as sometimes you don't really care, but with named arguments you usually do care and it would get confusing having 2 different behaviours. My suggestion is an `Opt` (for optional) contract for explicitly specifying when you don't mind if no value is provided, but unlike `Maybe` it treats `nil` as a value.

Yeah there is no way to get default values from a method, Ruby's reflection is pretty terrible sadly. You can get the `.parameters()` but that just returns a hash of [:type, :name] tuples, no default.

**Comment by waterlink** [comment]
So, given thought about @sfcgeorge comment, I would go with something like that:

```ruby
Contract Num, OptHash[b: Num, c: Opt[Num]] => None
def the_method(a, b:, c: 42)
  # ...
end
```

`OptHash` is the contract for defining a special case of `Hash` contract specifically for the quirks of ruby 2.0+ keyword arguments.

`Opt` contract can be used only inside of `OptHash` contract. Effectively makes a key, it is used on, optional. All keys, that don't use `Opt` contract will be considered required. When used outside of `OptHash` contract, will fail with descriptive error.

I think I can tackle this in a PR if nobody else want to do that? - this should involve only adding 2 built-in contracts and no change to contracts mechanics code.

**Comment by sfcgeorge** [comment]
`ReqHash` would make more sense as a name I think, as it's making keys required unless explicitly made `Opt`. Though to be less cryptic about what it's actually for, how about `NamedArgs`? Otherwise it seems a good idea.

**Comment by gsinclair** [comment]
Yes, NamedArgs is a good name 💜
